### ISSUE TITLE
Add support for `Generator<void>`

### ISSUE THREAD

**Issue by syyyr** [danvratil/qcoro#100]
`Generator<void>` is useful for creating a simple synchronous coroutine that can be paused and resumed with no other special functionality. As of now `Generator<void>` in a compile error.

Example usecase: a test driver function for testing a program that uses some sort of an asynchronous messaging mechanism

```cpp
#include <QCoroGenerator>

struct Connection;
Connection* get_connection();
auto conn = get_connection();

struct Message;
Message currentMessage;

QCoro::Generator<void> test_driver()
{
    co_yield;
    check_message_ok(currentMessage);
    conn->sendMessage(...);
    co_yield;
    check_message_ok(currentMessage);
    conn->sendMessage(...);

    //
    // ...
    //

    co_return;
}

struct App;
App* create_app(Connection*);

int main(int argc, char* argv[])
{
    auto driver = test_driver();
    auto it = driver.begin();

    auto app = create_app(conn);

    connect(conn, &Connection::messageReceived, [&] (const auto& msg) {
        currentMessage = msg;
        ++it;
        if (it == driver.end()) {
            app->exit(0);
        }
    });

    app->exec();
}
```

**Comment by danvratil** [comment]
While I get the idea, unfortunatelly this is not possible (at least not the way you outlined it). As per the standard, `co_yield` must be followed by an expression, just `co_yield;` is not a valid statement.

See [Godbolt](https://godbolt.org/z/v6oe15xan) and the [C++ standard](https://eel.is/c++draft/expr.yield#nt:yield-expression).

For your usecase, you'll probably have to do with some empty dummy type.
