### ISSUE TITLE
Initial release?

### ISSUE THREAD

**Issue by nicolasfella** [danvratil/qcoro#11]
I'd like to use qcoro in my (KDE) projects. Distros hate shipping stuff from git main branch, so it would be nice to have some form of release. A git tag should do, a downloadable tarball would be even better.

**Comment by danvratil** [comment]
That's a good point. I'll fix a few last things (fix what looks like a double-free on Linux, finalize Windows support) and I'll tag 0.1 release. I should be able to do it this week.

**Comment by danvratil** [comment]
Aaand done: https://www.dvratil.cz/2021/08/first-qcoro-release/ (the tag is v0.1.0)

Sorry it took so long...

**Comment by nicolasfella** [comment]
No problem, thanks a lot!
