### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by Philippe91** [danvratil/qcoro#118]
On the documentation site, the "Continue Reading" links of QCoro 0.6.0 Release Announcement and others, jump to nothing.
(https://qcoro.dvratil.cz/news/#blog-p1)

Also, the way the QCoro 0.6 introduction is written is misleading in the sense one could think "apple-clang support" is deprecated, while I think you mean the opposite.

**Comment by danvratil** [comment]
Thanks for the report! I fixed the bug in docs and adjusted the perex to be less ambiguous.
