### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by JBBgameich** [danvratil/qcoro#199]
Hey,

I have some code in one of my KDE projects that depends on this fix: https://github.com/danvratil/qcoro/commit/a7890a50b45fc601b8ab9d53ed2b8dde5e0e0dc1.
However that is not in any release yet.
Since the next release of my project is supposed to be sometime in January, is there a new QCoro release planned until then?

**Comment by danvratil** [comment]
Fair point. I'll do a release  :)

**Comment by danvratil** [comment]
0.10.0 has been released and announced.

vcpkg will be updated tomorrow, I have to wait for everything to build.
