### ISSUE TITLE
DBUILD_SHARED_LIBS missing form cmakeList

### ISSUE THREAD

**Issue by reg31** [danvratil/qcoro#230]
Hi,

I do not have the option to build qcoro as shared library in cmake.

**Comment by danvratil** [comment]
It's a CMake variable, so I did not explicitly mention it in my CMakeListst.txt. But passing `-DBUILD_SHARED_LIBS=ON` to CMake should work just fine to build QCoro as shared libraries. Or it doesn't work for you? Could you please share the cmake command you are using and full output from CMake?

**Comment by danvratil** [comment]
It's a CMake variable, so I did not explicitly mention it in my CMakeListst.txt. But passing `-DBUILD_SHARED_LIBS=ON` to CMake should work just fine to build QCoro as shared libraries. Or it doesn't work for you? Could you please share the cmake command you are using and full output from CMake?

**Comment by reg31** [comment]
It's ok, I've just added option(BUILD_SHARED_LIBS "Build using shared libraries" ON) to the cmakelist and it worked.

**Comment by danvratil** [comment]
Closing the issue, you can either add the option or just pass `-DBUILD_SHARED_LIBS=ON` to cmake when configuring QCoro.
