### ISSUE TITLE
Rename BUILD_TESTING to QCORO_BUILD_TESTING 

### ISSUE THREAD

**Issue by kelteseth** [danvratil/qcoro#233]
Examples and testing executables are features that I do not need when consuming the library. Now, I can easily disable them in my `CMakePresets.json`, but `BUILD_TESTING` should have the `QCORO_` prefix and a dedicated option. Now I have to hope that no other third party library that I use, uses the same flag :)

![image](https://github.com/user-attachments/assets/3a839626-c773-48fc-85eb-367954dfed2e)

**Comment by danvratil** [comment]
Hi, `BUILD_TESTING` is a [standard CMake option](https://cmake.org/cmake/help/latest/module/CTest.html) to toggle whether tests are built or not.

Depending on how you are using the library you can turn them off selectively - if you are using [ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html), just pass `-DBUILD_TESTING=OFF` in the configure step. If you are just using `add_subdirectory()` on a git submodule, you can `set(BUILD_TESTING OFF)` before adding the subdirectory and then either restore it to its previous value or turn it back on afterwards.

Although I see no harm in adding QCORO_ENABLE_TESTING to disable building QCoro tests, alongside the BUILD_TESTING variable itself.
