### ISSUE TITLE
Qt5 and Qt6 versions use the same filename and soname

### ISSUE THREAD

**Issue by berolinux** [danvratil/qcoro#36]
Qt 5 and Qt 6 versions of QCoro use the same filename and soname, so they can't coexist on the same system without using rpath tricks and/or LD_LIBRARY_PATH/LD_PRELOAD and friends.
It may make sense to use a naming scheme similar to Qt's own libraries (--> libQt5Coro.so.* / libQt6Coro.so.*)

**Comment by danvratil** [comment]
Good point, I shall indeed fix that.

I'll probably do libQCoro*5.so.* and libQCoro*6.so.* (I don't want to use the Qt scheme as that might make it confusing since QCoro is not part of Qt.
